TARGETS_EXERCISES_TEMPLATE_MPI:=exercise_2_1 exercise_2_2
TARGETS_EXERCISES_TEMPLATE_BLAS:=exercise_1_1 exercise_1_2 exercise_1_3
TARGETS_EXERCISES_SOLUTIONS_MPI:=2.1.mxm_static_scattering_col_alloc 2.1.mxm_static_scattering_row_alloc

TARGETS_EXERCISES:=$(TARGETS_EXERCISES_TEMPLATE_BLAS) $(TARGETS_EXERCISES_TEMPLATE_MPI) $(TARGETS_EXERCISES_SOLUTIONS_MPI)

.PHONY: exercises
exercises: $(TARGETS_EXERCISES)

EXERCISES_SRC_DIR:=$(patsubst %/, %, $(dir $(realpath $(lastword $(MAKEFILE_LIST)))))
EXERCISES_OBJ_DIR:=$(strip $(OBJ_DIR))/exercises

.PHONY: $(TARGETS_EXERCISES_TEMPLATE_BLAS)
$(TARGETS_EXERCISES_TEMPLATE_BLAS): %: $(BIN_DIR)/%

BLAS_COMPILE_OPTIONS:=$(shell pkgconf --cflags $(BLAS_LIB))
BLAS_LINK_OPTIONS:=$(shell pkgconf --libs $(BLAS_LIB))

$(patsubst %, $(BIN_DIR)/%, $(TARGETS_EXERCISES_TEMPLATE_BLAS)): $(BIN_DIR)/%: $(EXERCISES_OBJ_DIR)/%.o $(LIB_DIR)/libarray.a | $(BIN_DIR)
	$(CC) $(LDFLAGS) $^ $(LIB_ARRAY_LINK_OPTIONS_PUBLIC) $(BLAS_LINK_OPTIONS) -lm -o $@

$(patsubst %, $(EXERCISES_OBJ_DIR)/%.o, $(TARGETS_EXERCISES_TEMPLATE_BLAS)): $(EXERCISES_OBJ_DIR)/%.o: $(EXERCISES_SRC_DIR)/%.c $(LIB_ARRAY_HEADERS_PUBLIC) | $(EXERCISES_OBJ_DIR)
	$(CC) -c $(CFLAGS) -I$(INCLUDE_DIR) $(BLAS_COMPILE_OPTIONS) $< -o $@

.PHONY: $(TARGETS_EXERCISES_TEMPLATE_MPI)
$(TARGETS_EXERCISES_TEMPLATE_MPI): %: $(BIN_DIR)/%

$(patsubst %, $(BIN_DIR)/%, $(TARGETS_EXERCISES_TEMPLATE_MPI)): $(BIN_DIR)/%: $(EXERCISES_OBJ_DIR)/%.o $(LIB_DIR)/libmultiply.a $(LIB_DIR)/libarray.a | $(BIN_DIR)
	$(MPICC) $(LDFLAGS) $^ $(LIB_ARRAY_LINK_OPTIONS_PUBLIC) $(LIB_MULTIPLY_LINK_OPTIONS_PUBLIC) -o $@

$(patsubst %, $(EXERCISES_OBJ_DIR)/%.o, $(TARGETS_EXERCISES_TEMPLATE_MPI)): $(EXERCISES_OBJ_DIR)/%.o: $(EXERCISES_SRC_DIR)/%.c $(LIB_MULTIPLY_HEADERS_PUBLIC) $(LIB_ARRAY_HEADERS_PUBLIC) | $(EXERCISES_OBJ_DIR)
	$(MPICC) -c $(CFLAGS) -I$(INCLUDE_DIR) $< -o $@

.PHONY: $(TARGETS_EXERCISES_SOLUTIONS_MPI)
$(TARGETS_EXERCISES_SOLUTIONS): %: $(BIN_DIR)/%

$(patsubst %, $(BIN_DIR)/%, $(TARGETS_EXERCISES_SOLUTIONS_MPI)): $(BIN_DIR)/%: $(EXERCISES_OBJ_DIR)/%.o $(LIB_DIR)/libmultiply.a $(LIB_DIR)/libarray.a | $(BIN_DIR)
	$(MPICC) $(LDFLAGS) $^ $(LIB_ARRAY_LINK_OPTIONS_PUBLIC) $(LIB_MULTIPLY_LINK_OPTIONS_PUBLIC) -o $@

$(patsubst %, $(EXERCISES_OBJ_DIR)/%.o, $(TARGETS_EXERCISES_SOLUTIONS_MPI)): $(EXERCISES_OBJ_DIR)/%.o: $(EXERCISES_SRC_DIR)/solutions/%.c $(LIB_MULTIPLY_HEADERS_PUBLIC) $(LIB_ARRAY_HEADERS_PUBLIC) | $(EXERCISES_OBJ_DIR)
	$(MPICC) -c $(CFLAGS) -I$(INCLUDE_DIR) $< -o $@
