TARGETS_SIMPLE_EXAMPLES_BARE:=1.1.MPI_hello_world 2.1.MPI_bcast
TARGETS_SIMPLE_EXAMPLES_BARE_CONDITIONAL_MPI:=1.2.MPI_hello_world_PP
TARGETS_SIMPLE_EXAMPLES_WITH_UTILS:=2.2.MPI_bcast_arrays 2.3.MPI_bcast_matrices_error 2.4.MPI_bcast_matrices_vs1 2.5.MPI_bcast_matrices_vs2 3.1.MPI_send_recv_arrays 4.1.MPI_scatter_gather_arrays 5.1.MPI_reduce_allreduce

TARGETS_SIMPLE_EXAMPLES=$(TARGETS_SIMPLE_EXAMPLES_BARE) $(TARGETS_SIMPLE_EXAMPLES_BARE_CONDITIONAL_MPI) $(TARGETS_SIMPLE_EXAMPLES_WITH_UTILS)

.PHONY: simple_examples
simple_examples: $(TARGETS_SIMPLE_EXAMPLES)

SIMPLE_EXAMPLES_SRC_DIR:=$(patsubst %/, %, $(dir $(realpath $(lastword $(MAKEFILE_LIST)))))
SIMPLE_EXAMPLES_OBJ_DIR:=$(strip $(OBJ_DIR))/simple_examples

.PHONY: $(TARGETS_SIMPLE_EXAMPLES_BARE)
$(TARGETS_SIMPLE_EXAMPLES_BARE): %: $(BIN_DIR)/%

$(patsubst %, $(BIN_DIR)/%, $(TARGETS_SIMPLE_EXAMPLES_BARE)): $(BIN_DIR)/%: $(SIMPLE_EXAMPLES_OBJ_DIR)/%.o | $(BIN_DIR)
	$(MPICC) $(LDFLAGS) $^ -o $@

$(patsubst %, $(SIMPLE_EXAMPLES_OBJ_DIR)/%.o, $(TARGETS_SIMPLE_EXAMPLES_BARE)): $(SIMPLE_EXAMPLES_OBJ_DIR)/%.o: $(SIMPLE_EXAMPLES_SRC_DIR)/%.c | $(SIMPLE_EXAMPLES_OBJ_DIR)
	$(MPICC) -c $(CFLAGS) $< -o $@

.PHONY: $(TARGETS_SIMPLE_EXAMPLES_WITH_UTILS)
$(TARGETS_SIMPLE_EXAMPLES_WITH_UTILS): %: $(BIN_DIR)/%

$(patsubst %, $(BIN_DIR)/%, $(TARGETS_SIMPLE_EXAMPLES_WITH_UTILS)): $(BIN_DIR)/%: $(SIMPLE_EXAMPLES_OBJ_DIR)/%.o $(LIB_DIR)/libarray.a | $(BIN_DIR)
	$(MPICC) $(LDFLAGS) $^ $(LIB_ARRAY_LINK_PUBLIC) -o $@

$(patsubst %, $(SIMPLE_EXAMPLES_OBJ_DIR)/%.o, $(TARGETS_SIMPLE_EXAMPLES_WITH_UTILS)): $(SIMPLE_EXAMPLES_OBJ_DIR)/%.o: $(SIMPLE_EXAMPLES_SRC_DIR)/%.c $(LIB_ARRAY_HEADERS_PUBLIC) | $(SIMPLE_EXAMPLES_OBJ_DIR)
	$(MPICC) -c $(CFLAGS) -I$(INCLUDE_DIR) $< -o $@

.PHONY: $(TARGETS_SIMPLE_EXAMPLES_BARE_CONDITIONAL_MPI)
$(TARGETS_SIMPLE_EXAMPLES_BARE_CONDITIONAL_MPI): %: UPDATE__MPI_CACHE $(BIN_DIR)/%

$(patsubst %, $(BIN_DIR)/%, $(TARGETS_SIMPLE_EXAMPLES_BARE_CONDITIONAL_MPI)): $(BIN_DIR)/%: $(SIMPLE_EXAMPLES_OBJ_DIR)/%.o | $(BIN_DIR)
	$(MPICC_FLEX) $(LDFLAGS) $^ -o $@

$(patsubst %, $(SIMPLE_EXAMPLES_OBJ_DIR)/%.o, $(TARGETS_SIMPLE_EXAMPLES_BARE_CONDITIONAL_MPI)): $(SIMPLE_EXAMPLES_OBJ_DIR)/%.o: $(SIMPLE_EXAMPLES_SRC_DIR)/%.c $(_MPI_CACHE) | $(SIMPLE_EXAMPLES_OBJ_DIR)
	$(MPICC_FLEX) -c $(CFLAGS_FLEX) $< -o $@
